// Emits client-web/src/lib/plugins/foreign/shims/generated/dom-source.ts.
//
//   bun tool/gen-plugin-runtime.ts
//
// ## Why this exists
//
// A converted plugin bundle is ONE self-contained ES2020 module (ABI.md §1).
// The sandbox has no module resolution, so a converted scraper cannot import
// the HTML parser it was written against — the parser has to be *inside* the
// bundle, as source text.
//
// `shims/dom.ts` (a jsoup-shaped parser and selector engine) and
// `extract/patterns.ts` (deobfuscation that executes nothing) are both
// dependency-free and both already written to the engine subset, so they can be
// bundled and inlined verbatim. `shims/runtime-entry.ts` names exactly which of
// their exports cross that line.
//
// Generated and committed, rather than built at conversion time, for the same
// reason contract/build/tokens.css is: what ships must be reviewable in a diff,
// and a converted bundle's digest must be a fact about its input rather than
// about which machine converted it. `bun tool/gen-plugin-runtime.ts --check`
// is the drift gate (also `bun run check:generated` from client-web); the
// companion `shims/dom-source.spec.ts` checks the committed copy evaluates and
// still exports what the entry shims call.
//
// The output is embedded as a JSON string literal, not a template literal.
// The parser's source contains backticks and `${`, and escaping those into a
// template literal is a correctness problem with no upside — JSON.stringify is
// total, and the engines all parse a long double-quoted string fine.

import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';

const shims = fileURLToPath(new URL('../../runtime/src/shims/', import.meta.url));
const entry = `${shims}runtime-entry.ts`;
const outDir = `${shims}generated/`;
const outFile = `${outDir}dom-source.ts`;
const manifest = fileURLToPath(new URL('../../../package.json', import.meta.url));

/**
 * The bun this artefact is reproducible under, as `major.minor`, read from the
 * `packageManager` field so the version is declared in one place.
 */

/**
 * The generator runs under a pinned bun, and only under one: bundler identifier
 * renaming is not stable across minors, so the generated bytes would change for
 * a reason nobody asked for. Declared rather than widening `types` for the
 * whole workspace, because nothing else here may use it.
 */
declare const Bun: {
	readonly version: string;
	build(options: unknown): Promise<{
		success: boolean;
		logs: unknown[];
		outputs: { text(): Promise<string> }[];
	}>;
};
export function pinnedBun(manifestSource: string): string {
	const declared = (JSON.parse(manifestSource) as { packageManager?: string }).packageManager;
	const match = /^bun@(\d+)\.(\d+)\./.exec(declared ?? '');
	if (match === null) {
		throw new Error(
			`client-web/package.json needs a "packageManager": "bun@<x.y.z>" field; found ${String(declared)}`
		);
	}
	return `${match[1]}.${match[2]}`;
}

/**
 * Refuse to build under a bun that would emit different bytes for the same input.
 *
 * `minify.identifiers: false` stops the *mangling*, not the renaming bun does
 * when flattening scopes, and that renaming is not stable across bun minors:
 * 1.3.x and 1.4.x disagree about whether two block-scoped `digits` in one
 * function need to become `digits` and `digits2`. The output is semantically
 * identical either way, which is exactly what makes it expensive — `--check`
 * reports "stale", the obvious response is to regenerate and commit, and that
 * inverts the failure for everyone still on the pinned bun.
 *
 * So the version is a build input, and an unpinned one is caught here rather
 * than diagnosed later from a diff that looks like drift and is not. Verified
 * byte-identical across 1.3.0 and 1.3.14; 1.4.2 differs.
 *
 * Moving the pin is deliberate: change `packageManager`, regenerate, and commit
 * the new artefact with it — one commit, so the bytes and the bun that made
 * them never disagree in history.
 */
export function assertPinnedBun(running: string, pinned: string): void {
	if (running.startsWith(`${pinned}.`)) return;
	throw new Error(
		`this generator is pinned to bun ${pinned}.x and is running under ${running}.\n` +
			`Bundler identifier renaming differs across bun minors, so a build here would\n` +
			`report drift that is not drift. Run it under bun ${pinned}.x, or move the pin\n` +
			`deliberately: update "packageManager" in client-web/package.json, regenerate,\n` +
			`and commit the artefact together with the new pin.`
	);
}

/** Builds the runtime to one IIFE that assigns `globalThis.__yorozoRuntime`. */
export async function buildRuntimeSource(): Promise<string> {
	const built = await Bun.build({
		entrypoints: [entry],
		format: 'iife',
		target: 'browser',
		// Minified: this is machine output nobody reviews line by line, it is
		// carried in every converted bundle, and the readable original is right
		// there in the repository. Not mangled beyond bun's default, so a stack
		// trace out of the sandbox still names the failing function.
		minify: { whitespace: true, syntax: true, identifiers: false }
	});

	if (!built.success) {
		const reasons = built.logs.map((log: unknown) => String(log)).join('\n');
		throw new Error(`the plugin runtime did not build:\n${reasons}`);
	}
	if (built.outputs.length !== 1) {
		// More than one output means a chunk was split out, and a chunk is a
		// second file the bundle has no way to load.
		throw new Error(`expected one output, got ${built.outputs.length}`);
	}
	return await built.outputs[0].text();
}

export function renderModule(source: string): string {
	return `// GENERATED by tool/gen-plugin-runtime.ts — do not edit.
//
// The HTML parser and deobfuscation helpers, bundled as source so they can be
// inlined into a converted plugin bundle. See the generator for why, and
// shims/runtime-entry.ts for what is included.
//
// Run \`bun tool/gen-plugin-runtime.ts\` after changing shims/dom.ts,
// extract/patterns.ts or shims/runtime-entry.ts.

/** An IIFE that assigns \`globalThis.__yorozoRuntime\`. */
export const DOM_RUNTIME_SOURCE = ${JSON.stringify(source)};
`;
}

/**
 * The subcommand entry: `generate` writes, `generate --check` only compares.
 *
 * `--check` is the drift gate: it rebuilds and compares against what is
 * committed, so an edit to `dom.ts` that was never regenerated fails here
 * instead of shipping a stale parser inside every converted bundle. It lives on
 * the generator rather than in a spec because rebuilding needs the bundler, and
 * a spec that reached outside its own package to run one would be testing the
 * build system rather than the code.
 */
export async function runGenerate(argv: string[]): Promise<number> {
	assertPinnedBun(Bun.version, pinnedBun(readFileSync(manifest, 'utf8')));

	const rendered = renderModule(await buildRuntimeSource());

	if (argv.includes('--check')) {
		const committed = existsSync(outFile) ? readFileSync(outFile, 'utf8') : '';
		if (committed === rendered) {
			process.stdout.write('plugin runtime is up to date\n');
			return 0;
		}
		process.stderr.write(
			`${outFile} is stale.\nRun \`plugin-bridge generate\` and commit the result.\n`
		);
		return 1;
	}

	mkdirSync(outDir, { recursive: true });
	writeFileSync(outFile, rendered, 'utf8');
	process.stdout.write(`wrote ${outFile}\n`);
	return 0;
}
